### ISSUE TITLE
Unable to create new case

### ISSUE THREAD

**Issue by Pi1OuT** [EC-DIGIT-CSIRC/sysdiagnose#112]
Hi,

I've been trying to use this tool today and I'm facing an issue I could not find info about.
I've installed sysdiagnose as per the install guide and it seems to work:

```
sysdiag cases
#### case List ####
Case ID    acquisition date    Serial number    Unique device ID    iOS Version    Tags
---------  ------------------  ---------------  ------------------  -------------  ------

```

But as soon as I try to create a new case by importing a sysdiagnose tar, I get the following:

`sysdiag init ./sysdiagnose.tar.gz
Error creating case: 'dict' object has no attribute 'append'`

I'm not sure if I'm doing something wrong and I'm st*pid (which is always a possibility) or there is an issue with the current build.

Thanks !

**Comment by ancailliau** [comment]
Same issue reproduced with iOS 18.0.1.

Here is a trace
```
Traceback (most recent call last):
  File "/Users/acailliau/Projects/hacklu2024/sysdiagnose/sysdiagnose/venv/bin/sysdiag", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/acailliau/Projects/hacklu2024/sysdiagnose/sysdiagnose/src/sysdiagnose/main.py", line 104, in main
    case_id = sd.create_case(filename, force)['case_id']
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/acailliau/Projects/hacklu2024/sysdiagnose/sysdiagnose/src/sysdiagnose/__init__.py", line 144, in create_case
    remotectl_dumpstate_json = remotectl_dumpstate_parser.get_result()
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/acailliau/Projects/hacklu2024/sysdiagnose/sysdiagnose/src/sysdiagnose/utils/base.py", line 127, in get_result
    self._result = self.execute()
                   ^^^^^^^^^^^^^^
  File "/Users/acailliau/Projects/hacklu2024/sysdiagnose/sysdiagnose/src/sysdiagnose/parsers/remotectl_dumpstate.py", line 26, in execute
    return parse_tab_based_hierarchal_file(self.get_log_files()[0])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/acailliau/Projects/hacklu2024/sysdiagnose/sysdiagnose/src/sysdiagnose/utils/tabbasedhierarchy.py", line 8, in parse_tab_based_hierarchal_file
    result = parse_block(lines)
             ^^^^^^^^^^^^^^^^^^
  File "/Users/acailliau/Projects/hacklu2024/sysdiagnose/sysdiagnose/src/sysdiagnose/utils/tabbasedhierarchy.py", line 42, in parse_block
    result[key] = parse_block(extracted_block)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/acailliau/Projects/hacklu2024/sysdiagnose/sysdiagnose/src/sysdiagnose/utils/tabbasedhierarchy.py", line 42, in parse_block
    result[key] = parse_block(extracted_block)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/acailliau/Projects/hacklu2024/sysdiagnose/sysdiagnose/src/sysdiagnose/utils/tabbasedhierarchy.py", line 67, in parse_block
    result.append(line.strip())
    ^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'append'
```

**Comment by cvandeplas** [comment]
This should be fixed now as #114

**Comment by cvandeplas** [comment]
@Pi1OuT  can you check again and confirm please?

**Comment by Pi1OuT** [comment]
> @Pi1OuT can you check again and confirm please?

I confirm, the latest version fixes the issue. Thanks !

**Comment by cvandeplas** [comment]
excellent, thanks for the feedback.
