### ISSUE TITLE
Parser crashlogs crashes "Unexpected line"

### ISSUE THREAD

**Issue by ancailliau** [EC-DIGIT-CSIRC/sysdiagnose#113]
Bug with iOS 18.0.1

```
Parser 'crashlogs' for case ID '1'
[WARNING] [crashlogs] Skipping file due to error ./cases/1/data/[REDACTED]/crashes_and_spins/SpringBoard.diskwrites_resource-2024-10-24-022224.ips
Traceback (most recent call last):
  File "/Users/[redacted]/Projects/hacklu2024/sysdiagnose/sysdiagnose/src/sysdiagnose/parsers/crashlogs.py", line 55, in execute
    ips = CrashLogsParser.parse_ips_file(file)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/[redacted]/Projects/hacklu2024/sysdiagnose/sysdiagnose/src/sysdiagnose/parsers/crashlogs.py", line 119, in parse_ips_file
    raise Exception(f"Parser bug: Unexpected line in crashlogs at line {n}. Line: {line}")
Exception: Parser bug: Unexpected line in crashlogs at line 91. Line: 38  ??? (libsystem_pthread.dylib + 5256) [0x210c8c488]
```

**Comment by cvandeplas** [comment]
I've looked further at this and fortunately also have a file that has this behaviour.
Unfortunately I realise the parsing is much  more complex than originally thought.

It's also a reminder that I should run test cases more often on my larger dataset...
