### ISSUE TITLE
Parser remotectl_dumpstate crashes: 'dict' object has no attribute 'append'

### ISSUE THREAD

**Issue by ancailliau** [EC-DIGIT-CSIRC/sysdiagnose#114]
With iOS 18.0.1

```
$ sysdiag -c 1 parse remotectl_dumpstate
Case ID: 1
Parser 'remotectl_dumpstate' for case ID '1'
Traceback (most recent call last):
  File "[REDACTED]/sysdiagnose/sysdiagnose/venv/bin/sysdiag", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "[REDACTED]/sysdiagnose/sysdiagnose/src/sysdiagnose/main.py", line 148, in main
    result = sd.parse(parser, case_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[REDACTED]/sysdiagnose/sysdiagnose/src/sysdiagnose/__init__.py", line 186, in parse
    parser_instance.save_result(force=True)  # force parsing
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[REDACTED]/sysdiagnose/sysdiagnose/src/sysdiagnose/utils/base.py", line 148, in save_result
    f.write(json.dumps(self.get_result(force), ensure_ascii=False, indent=2, sort_keys=True))
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "[REDACTED]/sysdiagnose/sysdiagnose/src/sysdiagnose/utils/base.py", line 110, in get_result
    self._result = self.execute()
                   ^^^^^^^^^^^^^^
  File "[REDACTED]/sysdiagnose/sysdiagnose/src/sysdiagnose/parsers/remotectl_dumpstate.py", line 26, in execute
    return parse_tab_based_hierarchal_file(self.get_log_files()[0])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[REDACTED]/sysdiagnose/sysdiagnose/src/sysdiagnose/utils/tabbasedhierarchy.py", line 8, in parse_tab_based_hierarchal_file
    result = parse_block(lines)
             ^^^^^^^^^^^^^^^^^^
  File "[REDACTED]/sysdiagnose/sysdiagnose/src/sysdiagnose/utils/tabbasedhierarchy.py", line 42, in parse_block
    result[key] = parse_block(extracted_block)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[REDACTED]/sysdiagnose/sysdiagnose/src/sysdiagnose/utils/tabbasedhierarchy.py", line 42, in parse_block
    result[key] = parse_block(extracted_block)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[REDACTED]/sysdiagnose/sysdiagnose/src/sysdiagnose/utils/tabbasedhierarchy.py", line 67, in parse_block
    result.append(line.strip())
    ^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'append'

```

**Comment by ancailliau** [comment]
One of the failing file has the following structure:

```
	Properties: {
...
		EncryptedRemoteXPCPopulatedOIDs => [<capacity = 2>
			0: 1.2.840.113635.100.6.83
			1: 1.2.840.113635.100.6.84
		]
```

**Comment by cvandeplas** [comment]
Should be fixed now, thank you for reporting !

**Comment by ancailliau** [comment]
I confirm, I cannot reproduce the bug on the last commit 84e9cd690eccbfd65472d5966002d659ee7c8272
